/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as layoutsRouteRouteImport } from "./pages/(layouts)/route";
import { Route as LoginIndexRouteImport } from "./pages/login/index";
import { Route as layoutsOverviewIndexRouteImport } from "./pages/(layouts)/overview/index";
import { Route as layoutsFeaturesIndexRouteImport } from "./pages/(layouts)/features/index";
import { Route as layoutsDashboardIndexRouteImport } from "./pages/(layouts)/dashboard/index";
import { Route as layoutsComponentsIndexRouteImport } from "./pages/(layouts)/components/index";
import { Route as layoutsFeaturesResizeIndexRouteImport } from "./pages/(layouts)/features/resize/index";
import { Route as layoutsFeaturesMoveIndexRouteImport } from "./pages/(layouts)/features/move/index";
import { Route as layoutsFeaturesMinMaxIndexRouteImport } from "./pages/(layouts)/features/minMax/index";
import { Route as layoutsComponentsTreeIndexRouteImport } from "./pages/(layouts)/components/tree/index";

const layoutsRouteRoute = layoutsRouteRouteImport.update({
  id: "/(layouts)",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const layoutsOverviewIndexRoute = layoutsOverviewIndexRouteImport.update({
  id: "/overview/",
  path: "/overview/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsFeaturesIndexRoute = layoutsFeaturesIndexRouteImport.update({
  id: "/features/",
  path: "/features/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsDashboardIndexRoute = layoutsDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsComponentsIndexRoute = layoutsComponentsIndexRouteImport.update({
  id: "/components/",
  path: "/components/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsFeaturesResizeIndexRoute =
  layoutsFeaturesResizeIndexRouteImport.update({
    id: "/features/resize/",
    path: "/features/resize/",
    getParentRoute: () => layoutsRouteRoute,
  } as any);
const layoutsFeaturesMoveIndexRoute =
  layoutsFeaturesMoveIndexRouteImport.update({
    id: "/features/move/",
    path: "/features/move/",
    getParentRoute: () => layoutsRouteRoute,
  } as any);
const layoutsFeaturesMinMaxIndexRoute =
  layoutsFeaturesMinMaxIndexRouteImport.update({
    id: "/features/minMax/",
    path: "/features/minMax/",
    getParentRoute: () => layoutsRouteRoute,
  } as any);
const layoutsComponentsTreeIndexRoute =
  layoutsComponentsTreeIndexRouteImport.update({
    id: "/components/tree/",
    path: "/components/tree/",
    getParentRoute: () => layoutsRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/login": typeof LoginIndexRoute;
  "/components": typeof layoutsComponentsIndexRoute;
  "/dashboard": typeof layoutsDashboardIndexRoute;
  "/features": typeof layoutsFeaturesIndexRoute;
  "/overview": typeof layoutsOverviewIndexRoute;
  "/components/tree": typeof layoutsComponentsTreeIndexRoute;
  "/features/minMax": typeof layoutsFeaturesMinMaxIndexRoute;
  "/features/move": typeof layoutsFeaturesMoveIndexRoute;
  "/features/resize": typeof layoutsFeaturesResizeIndexRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginIndexRoute;
  "/components": typeof layoutsComponentsIndexRoute;
  "/dashboard": typeof layoutsDashboardIndexRoute;
  "/features": typeof layoutsFeaturesIndexRoute;
  "/overview": typeof layoutsOverviewIndexRoute;
  "/components/tree": typeof layoutsComponentsTreeIndexRoute;
  "/features/minMax": typeof layoutsFeaturesMinMaxIndexRoute;
  "/features/move": typeof layoutsFeaturesMoveIndexRoute;
  "/features/resize": typeof layoutsFeaturesResizeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(layouts)": typeof layoutsRouteRouteWithChildren;
  "/login/": typeof LoginIndexRoute;
  "/(layouts)/components/": typeof layoutsComponentsIndexRoute;
  "/(layouts)/dashboard/": typeof layoutsDashboardIndexRoute;
  "/(layouts)/features/": typeof layoutsFeaturesIndexRoute;
  "/(layouts)/overview/": typeof layoutsOverviewIndexRoute;
  "/(layouts)/components/tree/": typeof layoutsComponentsTreeIndexRoute;
  "/(layouts)/features/minMax/": typeof layoutsFeaturesMinMaxIndexRoute;
  "/(layouts)/features/move/": typeof layoutsFeaturesMoveIndexRoute;
  "/(layouts)/features/resize/": typeof layoutsFeaturesResizeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/login"
    | "/components"
    | "/dashboard"
    | "/features"
    | "/overview"
    | "/components/tree"
    | "/features/minMax"
    | "/features/move"
    | "/features/resize";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/components"
    | "/dashboard"
    | "/features"
    | "/overview"
    | "/components/tree"
    | "/features/minMax"
    | "/features/move"
    | "/features/resize";
  id:
    | "__root__"
    | "/(layouts)"
    | "/login/"
    | "/(layouts)/components/"
    | "/(layouts)/dashboard/"
    | "/(layouts)/features/"
    | "/(layouts)/overview/"
    | "/(layouts)/components/tree/"
    | "/(layouts)/features/minMax/"
    | "/(layouts)/features/move/"
    | "/(layouts)/features/resize/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  layoutsRouteRoute: typeof layoutsRouteRouteWithChildren;
  LoginIndexRoute: typeof LoginIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(layouts)": {
      id: "/(layouts)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof layoutsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(layouts)/overview/": {
      id: "/(layouts)/overview/";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof layoutsOverviewIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/features/": {
      id: "/(layouts)/features/";
      path: "/features";
      fullPath: "/features";
      preLoaderRoute: typeof layoutsFeaturesIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/dashboard/": {
      id: "/(layouts)/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof layoutsDashboardIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/components/": {
      id: "/(layouts)/components/";
      path: "/components";
      fullPath: "/components";
      preLoaderRoute: typeof layoutsComponentsIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/features/resize/": {
      id: "/(layouts)/features/resize/";
      path: "/features/resize";
      fullPath: "/features/resize";
      preLoaderRoute: typeof layoutsFeaturesResizeIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/features/move/": {
      id: "/(layouts)/features/move/";
      path: "/features/move";
      fullPath: "/features/move";
      preLoaderRoute: typeof layoutsFeaturesMoveIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/features/minMax/": {
      id: "/(layouts)/features/minMax/";
      path: "/features/minMax";
      fullPath: "/features/minMax";
      preLoaderRoute: typeof layoutsFeaturesMinMaxIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/components/tree/": {
      id: "/(layouts)/components/tree/";
      path: "/components/tree";
      fullPath: "/components/tree";
      preLoaderRoute: typeof layoutsComponentsTreeIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
  }
}

interface layoutsRouteRouteChildren {
  layoutsComponentsIndexRoute: typeof layoutsComponentsIndexRoute;
  layoutsDashboardIndexRoute: typeof layoutsDashboardIndexRoute;
  layoutsFeaturesIndexRoute: typeof layoutsFeaturesIndexRoute;
  layoutsOverviewIndexRoute: typeof layoutsOverviewIndexRoute;
  layoutsComponentsTreeIndexRoute: typeof layoutsComponentsTreeIndexRoute;
  layoutsFeaturesMinMaxIndexRoute: typeof layoutsFeaturesMinMaxIndexRoute;
  layoutsFeaturesMoveIndexRoute: typeof layoutsFeaturesMoveIndexRoute;
  layoutsFeaturesResizeIndexRoute: typeof layoutsFeaturesResizeIndexRoute;
}

const layoutsRouteRouteChildren: layoutsRouteRouteChildren = {
  layoutsComponentsIndexRoute: layoutsComponentsIndexRoute,
  layoutsDashboardIndexRoute: layoutsDashboardIndexRoute,
  layoutsFeaturesIndexRoute: layoutsFeaturesIndexRoute,
  layoutsOverviewIndexRoute: layoutsOverviewIndexRoute,
  layoutsComponentsTreeIndexRoute: layoutsComponentsTreeIndexRoute,
  layoutsFeaturesMinMaxIndexRoute: layoutsFeaturesMinMaxIndexRoute,
  layoutsFeaturesMoveIndexRoute: layoutsFeaturesMoveIndexRoute,
  layoutsFeaturesResizeIndexRoute: layoutsFeaturesResizeIndexRoute,
};

const layoutsRouteRouteWithChildren = layoutsRouteRoute._addFileChildren(
  layoutsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  layoutsRouteRoute: layoutsRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
