/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as layoutsRouteRouteImport } from "./pages/(layouts)/route";
import { Route as LoginIndexRouteImport } from "./pages/login/index";
import { Route as layoutsOverviewIndexRouteImport } from "./pages/(layouts)/overview/index";
import { Route as layoutsDashboardIndexRouteImport } from "./pages/(layouts)/dashboard/index";
import { Route as layoutsComponentsIndexRouteImport } from "./pages/(layouts)/components/index";
import { Route as layoutsComponentsTreeIndexRouteImport } from "./pages/(layouts)/components/tree/index";

const layoutsRouteRoute = layoutsRouteRouteImport.update({
  id: "/(layouts)",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const layoutsOverviewIndexRoute = layoutsOverviewIndexRouteImport.update({
  id: "/overview/",
  path: "/overview/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsDashboardIndexRoute = layoutsDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsComponentsIndexRoute = layoutsComponentsIndexRouteImport.update({
  id: "/components/",
  path: "/components/",
  getParentRoute: () => layoutsRouteRoute,
} as any);
const layoutsComponentsTreeIndexRoute =
  layoutsComponentsTreeIndexRouteImport.update({
    id: "/components/tree/",
    path: "/components/tree/",
    getParentRoute: () => layoutsRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/login": typeof LoginIndexRoute;
  "/components": typeof layoutsComponentsIndexRoute;
  "/dashboard": typeof layoutsDashboardIndexRoute;
  "/overview": typeof layoutsOverviewIndexRoute;
  "/components/tree": typeof layoutsComponentsTreeIndexRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginIndexRoute;
  "/components": typeof layoutsComponentsIndexRoute;
  "/dashboard": typeof layoutsDashboardIndexRoute;
  "/overview": typeof layoutsOverviewIndexRoute;
  "/components/tree": typeof layoutsComponentsTreeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(layouts)": typeof layoutsRouteRouteWithChildren;
  "/login/": typeof LoginIndexRoute;
  "/(layouts)/components/": typeof layoutsComponentsIndexRoute;
  "/(layouts)/dashboard/": typeof layoutsDashboardIndexRoute;
  "/(layouts)/overview/": typeof layoutsOverviewIndexRoute;
  "/(layouts)/components/tree/": typeof layoutsComponentsTreeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/login"
    | "/components"
    | "/dashboard"
    | "/overview"
    | "/components/tree";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/components"
    | "/dashboard"
    | "/overview"
    | "/components/tree";
  id:
    | "__root__"
    | "/(layouts)"
    | "/login/"
    | "/(layouts)/components/"
    | "/(layouts)/dashboard/"
    | "/(layouts)/overview/"
    | "/(layouts)/components/tree/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  layoutsRouteRoute: typeof layoutsRouteRouteWithChildren;
  LoginIndexRoute: typeof LoginIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(layouts)": {
      id: "/(layouts)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof layoutsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(layouts)/overview/": {
      id: "/(layouts)/overview/";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof layoutsOverviewIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/dashboard/": {
      id: "/(layouts)/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof layoutsDashboardIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/components/": {
      id: "/(layouts)/components/";
      path: "/components";
      fullPath: "/components";
      preLoaderRoute: typeof layoutsComponentsIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
    "/(layouts)/components/tree/": {
      id: "/(layouts)/components/tree/";
      path: "/components/tree";
      fullPath: "/components/tree";
      preLoaderRoute: typeof layoutsComponentsTreeIndexRouteImport;
      parentRoute: typeof layoutsRouteRoute;
    };
  }
}

interface layoutsRouteRouteChildren {
  layoutsComponentsIndexRoute: typeof layoutsComponentsIndexRoute;
  layoutsDashboardIndexRoute: typeof layoutsDashboardIndexRoute;
  layoutsOverviewIndexRoute: typeof layoutsOverviewIndexRoute;
  layoutsComponentsTreeIndexRoute: typeof layoutsComponentsTreeIndexRoute;
}

const layoutsRouteRouteChildren: layoutsRouteRouteChildren = {
  layoutsComponentsIndexRoute: layoutsComponentsIndexRoute,
  layoutsDashboardIndexRoute: layoutsDashboardIndexRoute,
  layoutsOverviewIndexRoute: layoutsOverviewIndexRoute,
  layoutsComponentsTreeIndexRoute: layoutsComponentsTreeIndexRoute,
};

const layoutsRouteRouteWithChildren = layoutsRouteRoute._addFileChildren(
  layoutsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  layoutsRouteRoute: layoutsRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
