packages:
  - apps/*
  - packages/*
  - packages/components/*
  - config/*
  - config/lint/*
  - docs/*

catalog:
  '@biomejs/biome': 2.3.7
  '@biomejs/monorepo': github:biomejs/biome
  '@commitlint/config-conventional': ^20.2.0
  '@commitlint/types': ^20.2.0
  '@diceui/listbox': ^0.2.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@eslint-react/eslint-plugin': ^2.4.0
  '@eslint/js': ^9.39.2
  '@hookform/resolvers': 5.2.2
  '@next/eslint-plugin-next': ^16.1.1
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': 1.2.8
  '@rsbuild/core': 1.6.7
  '@rsbuild/plugin-react': ^1.4.2
  '@rsbuild/plugin-svgr': ^1.2.3
  '@rsbuild/plugin-type-check': ^1.3.2
  '@stylistic/stylelint-plugin': ^4.0.0
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/eslint-plugin-router': ^1.141.0
  '@tanstack/react-query': 5.90.10
  '@tanstack/react-query-devtools': 5.91.0
  '@tanstack/react-router': ^1.144.0
  '@tanstack/react-router-devtools': ^1.144.0
  '@tanstack/react-table': ^8.21.3
  '@tanstack/react-virtual': ^3.13.14
  '@tanstack/router-plugin': 1.139.1
  '@types/lodash-es': ^4.17.12
  '@types/node': 24.10.1
  '@types/react': 19.2.6
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  ahooks: 3.9.6
  browserslist: ^4.28.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: ^1.1.1
  code-inspector-plugin: 1.3.0
  commitlint: ^20.2.0
  date-fns: ^4.1.0
  embla-carousel-react: ^8.6.0
  eslint: 9.39.1
  eslint-config-biome: 2.1.3
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  globals: ^16.5.0
  husky: ^9.1.7
  immer: ^10.2.0
  input-otp: ^1.4.2
  ky: ^1.14.2
  lightningcss: ^1.30.2
  lodash-es: ^4.17.22
  lucide-react: 0.554.0
  msw: 2.12.2
  next: ^16.1.1
  react: 19.2.0
  react-day-picker: 9.11.1
  react-dom: 19.2.0
  react-hook-form: 7.66.1
  react-resizable-panels: 3.0.6
  rollup-plugin-visualizer: ^6.0.5
  sonner: 2.0.7
  stylelint: 16.26.0
  stylelint-config-recess-order: ^7.4.0
  stylelint-order: ^7.0.1
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  turbo: ^2.7.2
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.51.0
  vaul: ^1.1.2
  vite: 7.2.4
  vite-plugin-compression: ^0.5.1
  vite-plugin-svgr: ^4.5.0
  zod: 4.1.12
  zustand: ^5.0.9

catalogMode: prefer

cleanupUnusedCatalogs: true
