packages:
  - apps/*
  - packages/*
  - packages/components/*
  - config/*
  - config/lint/*
  - docs/*

catalog:
  '@biomejs/biome': 2.3.11
  '@biomejs/monorepo': github:biomejs/biome
  '@bprogress/core': ^1.3.4
  '@commitlint/config-conventional': ^20.3.1
  '@commitlint/types': ^20.3.1
  '@diceui/listbox': ^0.2.0
  '@dnd-kit/core': 6.3.1
  '@dnd-kit/modifiers': 9.0.0
  '@dnd-kit/sortable': 10.0.0
  '@dnd-kit/utilities': 3.2.2
  '@eslint-react/eslint-plugin': ^2.7.2
  '@eslint/js': ^9.39.2
  '@hookform/resolvers': 5.2.2
  '@next/eslint-plugin-next': ^16.1.4
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': 1.2.8
  '@rsbuild/core': 1.7.2
  '@rsbuild/plugin-react': ^1.4.3
  '@rsbuild/plugin-svgr': ^1.2.4
  '@rsbuild/plugin-type-check': ^1.3.3
  '@stylistic/stylelint-plugin': ^5.0.1
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/eslint-plugin-query': ^5.91.3
  '@tanstack/eslint-plugin-router': ^1.154.7
  '@tanstack/react-query': 5.90.19
  '@tanstack/react-query-devtools': 5.91.2
  '@tanstack/react-router': ^1.154.12
  '@tanstack/react-router-devtools': ^1.154.12
  '@tanstack/react-table': ^8.21.3
  '@tanstack/react-virtual': ^3.13.18
  '@tanstack/router-plugin': 1.154.12
  '@types/lodash-es': ^4.17.12
  '@types/node': 25.0.10
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  ahooks: 3.9.6
  browserslist: ^4.28.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: ^1.1.1
  code-inspector-plugin: 1.3.6
  commitlint: ^20.3.1
  date-fns: ^4.1.0
  embla-carousel-react: ^8.6.0
  eslint: 9.39.2
  eslint-config-biome: 2.1.3
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  globals: ^17.1.0
  husky: ^9.1.7
  immer: ^11.1.3
  input-otp: ^1.4.2
  ky: ^1.14.2
  lightningcss: ^1.31.1
  lodash-es: ^4.17.23
  lucide-react: 0.562.0
  msw: 2.12.7
  next: ^16.1.4
  pinyin-pro: ^3.28.0
  react: 19.2.3
  react-day-picker: 9.13.0
  react-dom: 19.2.3
  react-hook-form: 7.71.1
  react-resizable-panels: 4.4.1
  rollup-plugin-visualizer: ^6.0.5
  sonner: 2.0.7
  stylelint: 17.0.0
  stylelint-config-recess-order: ^7.6.0
  stylelint-order: ^7.0.1
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  turbo: ^2.7.5
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.53.1
  vaul: ^1.1.2
  vite: 7.3.1
  vite-plugin-compression: ^0.5.1
  vite-plugin-svgr: ^4.5.0
  zod: 4.3.6
  zustand: ^5.0.10

catalogMode: prefer

cleanupUnusedCatalogs: true
